In [1]:
import pandas as pd
import numpy as np

In [2]:
info = {
    "Name": ["Rahul", "Harshita", "Shradha"],
    "CGPA": [9.5, 7.5, 8.5]
}
df = pd.DataFrame(info)
print(df)
print(type(df))

s = pd.Series([1, 2, 3, 4, 5])
print(s, s[2])
print(type(s))

       Name  CGPA
0     Rahul   9.5
1  Harshita   7.5
2   Shradha   8.5
<class 'pandas.core.frame.DataFrame'>
0    1
1    2
2    3
3    4
4    5
dtype: int64 3
<class 'pandas.core.series.Series'>

In [3]:
df

       Name  CGPA
0     Rahul   9.5
1  Harshita   7.5
2   Shradha   8.5

In [4]:
s = pd.Series([23, 24, 25, 26], index = ["Adam", "Eve", "Bob", "Charlie"])
print(s)
print(s["Adam"], s["Bob"], s.iloc[1], s.index)

Adam       23
Eve        24
Bob        25
Charlie    26
dtype: int64
23 25 24 Index(['Adam', 'Eve', 'Bob', 'Charlie'], dtype='object')

In [5]:
# Series
s1 = pd.Series([1, 2, 3, 4, 5])
s2 = pd.Series([10, 20, 30, 40, 50])
print(s1+s2)

s1[0] = 100
changed_s1 = s1.drop(0)
print(s1, changed_s1, sep="\n")

0    11
1    22
2    33
3    44
4    55
dtype: int64
0    100
1      2
2      3
3      4
4      5
dtype: int64
1    2
2    3
3    4
4    5
dtype: int64

In [6]:
# DataFrame
info = {
    "Name": ["Adam", "Eve", "Bob"],
    "Age": [24, 23, 22],
    "CGPA": [9.5, 8.6, 7.2]
}
df = pd.DataFrame(info, index=[1, 2, 3])
print(df, type(df))
print(df.index, df.columns)

   Name  Age  CGPA
1  Adam   24   9.5
2   Eve   23   8.6
3   Bob   22   7.2 <class 'pandas.core.frame.DataFrame'>
Index([1, 2, 3], dtype='int64') Index(['Name', 'Age', 'CGPA'], dtype='object')

In [7]:
df = pd.DataFrame([["Adam", 23], ["Bob", 24], ["Charlie", 25]], columns=["Name", "Age"])
print(df)

np_arr = np.array([[1, 2, 3], [4, 5, 6]])
df = pd.DataFrame(np_arr, columns=["A", "B", "C"])
print(df)

      Name  Age
0     Adam   23
1      Bob   24
2  Charlie   25
   A  B  C
0  1  2  3
1  4  5  6

In [30]:
# JSON Data
df = pd.read_json("employee_data.json")
print(df, type(df), sep="\n")

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000
5   6    Frank   29    Finance   50000
6   7    Grace   41         HR   82000
7   8   Hannah   26  Marketing   47000
8   9      Ian   35         IT   75000
9  10    Julia   30    Finance   60000
<class 'pandas.core.frame.DataFrame'>

In [31]:
# CSV Data
df = pd.read_csv("employee_data.csv")
print(df, type(df), sep="\n")

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000
5   6    Frank   29    Finance   50000
6   7    Grace   41         HR   82000
7   8   Hannah   26  Marketing   47000
8   9      Ian   35         IT   75000
9  10    Julia   30    Finance   60000
<class 'pandas.core.frame.DataFrame'>

In [32]:
df

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000
5   6    Frank   29    Finance   50000
6   7    Grace   41         HR   82000
7   8   Hannah   26  Marketing   47000
8   9      Ian   35         IT   75000
9  10    Julia   30    Finance   60000

In [35]:
# Methods
df.head() #starting 5 rows
df.tail(2) #trailing 5 rows
df.sample(3)
df.info()
df.shape
df.describe()
df.columns
df.nunique()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   ID          10 non-null     int64
 1   Name        10 non-null     object
 2   Age         10 non-null     int64
 3   Department  10 non-null     object
 4   Salary      10 non-null     int64
dtypes: int64(3), object(2)
memory usage: 532.0+ bytes

ID            10
Name          10
Age           10
Department     4
Salary        10
dtype: int64

In [10]:
# AQI Data Set
df = pd.read_csv("globalAirQuality.csv")
df.head()
df.tail()
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18000 entries, 0 to 17999
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   timestamp    18000 non-null  object
 1   country      18000 non-null  object
 2   city         18000 non-null  object
 3   latitude     18000 non-null  float64
 4   longitude    18000 non-null  float64
 5   pm25         18000 non-null  float64
 6   pm10         18000 non-null  float64
 7   no2          18000 non-null  float64
 8   so2          18000 non-null  float64
 9   o3           18000 non-null  float64
 10  co           18000 non-null  float64
 11  aqi          18000 non-null  int64
 12  temperature  18000 non-null  float64
 13  humidity     18000 non-null  float64
 14  wind_speed   18000 non-null  float64
dtypes: float64(11), int64(1), object(3)
memory usage: 2.1+ MB

,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
count,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000
mean,23.065980,37.655560,40.369131,70.152228,32.055176,6.035508,48.065100,0.800595,104.645556,21.510251,57.714351,5.283910
std,26.156536,78.600701,17.647450,24.999440,13.820680,2.454790,14.950849,0.250254,25.616070,9.509444,18.844908,2.741712
min,-37.814000,-123.121000,0.025000,0.061000,0.013000,0.003000,0.114000,0.000000,16.000000,5.000000,25.002000,0.500000
25%,12.972000,2.352000,27.904500,53.125500,22.362500,4.360750,38.028500,0.633000,87.000000,13.357750,41.320000,2.937000
50%,29.232000,42.146000,40.286500,69.961000,32.019500,6.026000,48.142000,0.800500,103.000000,21.455500,57.847000,5.297000
75%,41.008000,103.820000,52.436250,87.256500,41.364250,7.715250,58.258500,0.969000,121.000000,29.688250,74.234750,7.662000
max,60.170000,174.763000,115.683000,161.810000,90.019000,16.559000,103.016000,1.832000,231.000000,37.998000,89.997000,9.999000

In [39]:
# Selecting Data

#columns
df["country"]  #view of the data
df[["city", "aqi"]]

#rows
df.loc[2]
df.loc[0:2]  #start idx : end idx (inclusive)
df.iloc[2]
df.iloc[0:2]  #start idx : end idx (exclusive)

#cells - rows & columns
df.loc[0:2, ["city", "aqi"]]
df.columns
df.iloc[0:3, 1:5]

#cell
df.at[0, "city"]
df.iat[0, 2]

cities = df["city"].copy()
cities[0] = "Mumbai"
cities

0          Mumbai
1        New York
2        New York
3        New York
4        New York
           ...
17995      Zurich
17996      Zurich
17997      Zurich
17998      Zurich
17999      Zurich
Name: city, Length: 18000, dtype: object

In [55]:
# Filtering of Data
df[(df["aqi"] > 100) & (df["temperature"] > 30)]
df[(df["aqi"] > 100) & (df["temperature"] < 30)]
aqi_data = df[(df["aqi"] > 100) & (df["temperature"] > 30)][["city", "aqi"]]
aqi_data
aqi_data.loc[6]
aqi_data.iloc[0]

city    New York
aqi          155
Name: 6, dtype: object

In [62]:
# Query Method - returns copy
aqi_val = 100
aqi_data = df.query("aqi > @aqi_val & temperature > 30")[["city", "aqi"]].copy()

In [2]:
# Cleaning Data - missing values
df = pd.read_csv("raw_data.csv")
df
df.isnull()
df.isna().sum()
df.dropna() #row drop
df.dropna(axis=1) #col drop
cleaned_data = df.copy()
cleaned_data["age"] = cleaned_data["age"].fillna(cleaned_data["age"].mean())
cleaned_data["income"] = cleaned_data["income"].fillna(cleaned_data["income"].mean())
cleaned_data["name"] = cleaned_data["name"].ffill()
cleaned_data["country"] = cleaned_data["country"].bfill()
cleaned_data["gender"] = cleaned_data["gender"].ffill()
cleaned_data

    id          name    age country   gender   income
0    1      John Doe  29.00     USA     Male  55000.0
1    1      John Doe  29.00     USA     Male  55000.0
2    2    Jane Smith  32.75  Canada   Female  62000.0
3    3          Alex  32.75     USA  Unknown  47000.0
4    4  Maria Garcia  34.00   Spain   Female  57600.0
5    5        Li Wei  27.00   China     Male  51000.0
6    6        Li Wei  45.00   India   Female  73000.0
7    7    Ahmed Khan  38.00     USA     Male  68000.0
8    8    Rachel Lee  29.00     USA   Female  62000.0
9    9   Carlos Ruiz  32.75  Mexico     Male  45000.0
10  10   Emily Davis  31.00     USA     Male  58000.0

In [3]:
# Handle Duplicates
df[["country", "gender"]].duplicated()
df2 = df.copy()
df2.drop_duplicates(inplace=True)
df2

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

In [4]:
# Data Types
df.dtypes
df2 = df.copy()
df2 = df2.fillna(0)
df2["age"] = df2["age"].astype("int64")
df2.dtypes

id           int64
name        object
age          int64
country     object
gender      object
income     float64
dtype: object

In [5]:
aqi_data = pd.read_csv("globalAirQuality.csv")
aqi_data["timestamp"] = pd.to_datetime(aqi_data["timestamp"])
aqi_data["timestamp"].dtype

dtype('<M8[ns]')

In [6]:
date_str = pd.Series([pd.to_datetime("2026-12-31")])
date_str

0   2026-12-31
dtype: datetime64[ns]

In [11]:
# Handling Strings
df["gender"].str.lower()
df["gender"].str.upper()
df["gender"].str.capitalize()

df["name"].str.split(" ")
df["country"].str.contains("india", case=False)

0     False
1     False
2     False
3     False
4     False
5     False
6      True
7       NaN
8     False
9     False
10    False
Name: country, dtype: object